---
- hosts: all
  remote_user: ubuntu
  sudo: yes
  tasks:
    - name: Install packages
      apt: name={{ item }} state=present force=true
      with_items:
        - git-core
        - apache2
        - tomcat7
        - mysql-server-5.6

    - name: Enable service on start up
      service: name={{ item }} state=started enabled=yes
      with_items:
        - apache2
        - tomcat7
        - mysql
    - name: Create Tomcat7-a instance
      file: path=/var/lib/tomcat7-a state=directory mode=0777

    - name: Create Tomcat7-b instance
      file: path=/var/lib/tomcat7-b state=directory mode=0777

    - name: Create conf files for Tomcat instances
      file: path=/var/lib/tomcat7-a/{{ item }} state=directory mode=0777 owner=tomcat7
      with_items:
        - conf
        - temp
        - webapps
        - work
        - logs

    - name: Create conf files for Tomcat instances
      file: path=/var/lib/tomcat7-b/{{ item }} state=directory mode=0777 owner=tomcat7
      with_items:
        - conf
        - temp
        - webapps
        - work
        - logs
        
    - name: Link tomcat instance A
      file: src=/var/lib/tomcat7/conf/{{ item }} dest=/var/lib/tomcat7-a/conf/ state=link
      with_items:
        - catalina.properties
        - web.xml
        - server.xml
        - policy.d
      
    - name: Link tomcat instance B
      file: src=/var/lib/tomcat7/conf/{{ item }} dest=/var/lib/tomcat7-b/conf/ state=link
      with_items:
        - catalina.properties
        - web.xml
        - server.xml
        - policy.d
        
    - name: Instance A | Create Service
      copy: src=/etc/init.d/tomcat7 dest=/etc/init.d/{{ item }}
      with_items:
        - tomcat7-a
        - tomcat7-b
        
    - name: Create /usr/share/tomcat7 for new instances
      file: path=/usr/share/{{ item }} state=directory
      with_items:
       - tomcat7-a
       - tomcat7-b
       
    - name: Copy content to new instances
      copy: src=/usr/share/tomcat7/* dest=/usr/share/{{ item }}
      with_items:
       - tomcat7-a
       - tomcat7-b
      
    - name: Deploy application
      git: repo=https://github.com/sukhadas/ansible.git
           dest=/var/lib/{{ item }}/webapps/ansible
      with_items:
        - tomcat7-a
        - tomcat7-b
    - name: Delete configuration file of apache2 and replace with new one
      file: path=/etc/apache2/sites-enabled/000-default.conf state=absent
      
    - name: Adding already created Load balancing file
      file: src=./000-default.conf dest=/etc/apache2/sites-enabled/000-default.conf
      
    - name: Start all services
      service: name={{ item }} state=started enabled=yes
      with_items:
       - tomcat7
       - tomcat7-a
       - tomcat7-b
       - apache2
       - mysql
  
